cache:
  directories:
    - node_modules
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "lts"
  - "node"
install:
  - npm i
script: npm run test --maxWorkers=6 --ci
branches:
  only:
    - master
notifications:
  email: false
